Repository ajnart/homarr, pull requests merged in 2022-05, with the labels that each got.

#60 🛠️ fix: Docker action build
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
Labels: ✨ Enhancement

#65 fix: Center align Discord CTA
  README.md
Labels: ✨ Enhancement

#92 ♿️ Work on responsiveness for the AppShelf
  .github/workflows/docker_dev.yml
  src/components/AppShelf/AddAppShelfItem.tsx
  src/components/AppShelf/AppShelf.story.tsx
  src/components/AppShelf/AppShelf.tsx
  src/components/AppShelf/AppShelfItemWrapper.tsx
  src/components/Settings/SettingsMenu.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Logo.tsx
  src/components/layout/Navbar.tsx
Labels: 🐛 Bug, 🛠️ WIP

#142 Drag and drop ! (v0.5.0)
  next.config.js
  package.json
  src/components/AppShelf/AddAppShelfItem.tsx
  src/components/AppShelf/AppShelf.story.tsx
  src/components/AppShelf/AppShelf.tsx
  src/components/AppShelf/AppShelfItem.tsx
  src/components/AppShelf/AppShelfItemWrapper.tsx
  src/components/AppShelf/index.ts
  src/pages/_document.tsx
  yarn.lock
Labels: ✨ Feature
