Repository ajnart/homarr, pull requests merged in 2023-10, with the labels that each got.

#1420 🐛 Database error with readonly mappings
  src/middleware.ts
Labels: 🐛 Bug

#1434 ♻️ Migrate from prisma to drizzle
  .env.example
  .gitignore
  Dockerfile
  database/.gitkeep
  drizzle.config.ts
  drizzle/0000_supreme_the_captain.sql
  drizzle/meta/0000_snapshot.json
  drizzle/meta/_journal.json
  next-env.d.ts
  package.json
  prisma/schema.prisma
  scripts/run.sh
  src/components/Password/password-requirement.tsx
  src/env.js
  src/migrate.ts
  src/pages/auth/invite/[inviteId].tsx
  src/pages/board/[slug].tsx
  src/pages/board/index.tsx
  src/pages/manage/tools/docker.tsx
  src/pages/manage/users/index.tsx
  src/pages/onboard.tsx
  src/server/api/routers/board.ts
  src/server/api/routers/invite.ts
  src/server/api/routers/user.ts
  src/server/api/trpc.ts
  src/server/auth.ts
  src/server/db.ts
  src/server/db/index.ts
  src/server/db/queries/user.ts
  src/server/db/queries/userSettings.ts
  src/server/db/schema.ts
  src/widgets/calendar/CalendarTile.tsx
  tsconfig.json
  yarn.lock
Labels: 🏛️ Architecture

#1459 🔒️ Fix tiptap url CVE
  src/widgets/notebook/NotebookEditor.tsx
Labels: 🚨 Security Risk

#1483 🐛 Issue with migrate script in docker
  Dockerfile
  package.json
  scripts/run.sh
Labels: 🐛 Bug

#1487 🐛 Background image not visible, remove background image from default config
  data/configs/default.json
  src/components/layout/Templates/BoardLayout.tsx
Labels: 🐛 Bug

#1486 🐛 500 error when saving user settings, Language not applied after save of user preferences
  src/components/User/Preferences/Language/LanguageSelect.tsx
  src/pages/user/preferences.tsx
  src/server/api/routers/user.ts
Labels: 🐛 Bug

#1485 🐛 About version and dependencies not present
  src/pages/_app.tsx
Labels: 🐛 Bug

#1489 🐛 No validation messages when saving, Dirty state not reset, Wrong page title validation
  src/pages/board/[slug]/customize.tsx
  src/validations/boards.ts
Labels: 🐛 Bug

#1490 🐛 Issue with navigation drawer transitionProps
  src/components/layout/Templates/ManageLayout.tsx
Labels: 🐛 Bug

#1491 🐛 Common settings translation not included within all pages for about credits
  src/tools/server/getServerSideTranslations.ts
Labels: 🐛 Bug

#1508 ✨ Add 401 page
  public/locales/en/layout/errors/access-denied.json
  src/images/undraw_secure_login_pdn4.svg
  src/pages/401.tsx
  src/pages/board/[slug]/customize.tsx
  src/pages/board/index.tsx
  src/pages/manage/index.tsx
  src/pages/manage/tools/docker.tsx
  src/pages/manage/users/index.tsx
  src/pages/manage/users/invites.tsx
  src/tools/server/loginBuilder.ts
  src/tools/server/translation-namespaces.ts
Labels: ✨ Feature
