Repository ajnart/homarr, pull requests merged in 2023-11, with the labels that each got.

#1509 feat: add support for default ports on http(s) protocols on download.ts
  src/server/api/routers/download.ts
Labels: 🤔 Question, 📝 Needs more info

#1586 🐛 Fix podman issue
  scripts/run.sh
Labels: 🐛 Bug

#1584 🐛 Logo has no height and object-fit is not contain #1581
  src/components/layout/Common/Logo.tsx
Labels: 🐛 Bug

#1587 🐛 Placeholder width stretches out of screen
  src/styles/global.scss
Labels: 🐛 Bug

#1603 Corrected a typo in the Docker integration EN locale
  public/locales/en/tools/docker.json
Labels: 🐛 Bug

#1602 🐳 Improve dockerfile and start script and fix permission issue
  Dockerfile
  drizzle/migrate/migrate.ts
  drizzle/migrate/package.json
  package.json
  scripts/run.sh
  yarn.lock
Labels: 🐛 Bug

#1610 fix: customize page crashing for invalid board
  src/pages/board/[slug]/customize.tsx
Labels: 🐛 Bug

#1611 Fix issues with dockerfile
  Dockerfile
  data/default.json
  scripts/run.sh
  src/components/Onboarding/database-not-writeable.tsx
  src/middleware.ts
  src/pages/onboard.tsx
  src/tools/config/getFallbackConfig.ts
Labels: 🐛 Bug

#1630 🐛 File busy with node > 20.3
  Dockerfile
Labels: 🐛 Bug

#1629 SSR Optimize and add "Public" tag
  data/crowdin-report.json
  public/locales/en/common.json
  src/pages/board/index.tsx
  src/pages/manage/boards/index.tsx
  src/server/api/routers/board.ts
  src/tools/server/loginBuilder.ts
  tests/pages/board/[slug].spec.ts
Labels: 🐛 Bug

#1637 🐛 Error object not compatible with json parsing of gssp
  src/components/Onboarding/database-not-writeable.tsx
  src/pages/onboard.tsx
Labels: 🐛 Bug

#1654 🐛 Migrate package.json has no license field
  drizzle/migrate/package.json
Labels: 🐛 Bug

#1652 🐛 Link to definition of screen sized for edit mode notification wrong
  src/components/layout/Templates/BoardLayout.tsx
Labels: 🐛 Bug

#1663 Allow custom nextauth port
  scripts/run.sh
Labels: 🐛 Bug

#1675 ✨ Add support for installation in address bar
  public/site.webmanifest
Labels: ✨ Feature

#1658 feat: #698 homeassistant widget
  package.json
  public/locales/en/modules/smart-home/entity-state.json
  src/components/Dashboard/Modals/EditAppModal/Tabs/IntegrationTab/Components/InputElements/IntegrationSelector.tsx
  src/server/api/root.ts
  src/server/api/routers/smart-home/entity-state.ts
  src/tools/server/sdk/homeassistant/HomeAssistant.ts
  src/tools/server/sdk/homeassistant/models/EntityState.ts
  src/tools/server/translation-namespaces.ts
  src/tools/shared/strings.ts
  src/tools/singleton/HomeAssistantSingleton.ts
  src/types/app.ts
  src/widgets/index.ts
  src/widgets/smart-home/entity-state/entity-state.widget.tsx
Labels: ✨ Feature, 🎴 Widget

#1709 Update acceptableStatusCodes.ts
  src/tools/acceptableStatusCodes.ts
Labels: ✨ Feature
