Repository ajnart/homarr, pull requests merged in 2023-08, with the labels that each got.

#1229 💄 Media requests stats widget stretch elements to fit tile
  public/locales/en/modules/media-requests-stats.json
  src/widgets/media-requests/MediaRequestStatsTile.tsx
Labels: ✨ Feature

#1235 Adding 'audio' session type for Plex based on 'track' Plex API
  src/tools/server/sdk/plex/plexClient.ts
Labels: ✨ Feature

#1212 ✨ InfoCard
  package.json
  public/locales/en/common.json
  public/locales/en/modules/bookmark.json
  src/components/Dashboard/Tiles/Widgets/Inputs/LocationSelection.tsx
  src/components/Dashboard/Tiles/Widgets/WidgetsEditModal.tsx
  src/components/InfoCard/InfoCard.tsx
  src/widgets/bookmark/BookmarkWidgetTile.tsx
  src/widgets/widgets.ts
  yarn.lock
Labels: ✨ Feature

#1231 ✨App tile UI change
  public/locales/en/layout/modals/add-app.json
  src/components/Dashboard/Modals/EditAppModal/EditAppModal.tsx
  src/components/Dashboard/Modals/EditAppModal/Tabs/AppereanceTab/AppereanceTab.tsx
  src/components/Dashboard/Modals/EditAppModal/Tabs/BehaviourTab/BehaviourTab.tsx
  src/components/Dashboard/Modals/EditAppModal/Tabs/GeneralTab/GeneralTab.tsx
  src/components/Dashboard/Modals/EditAppModal/Tabs/NetworkTab/NetworkTab.tsx
  src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
  src/components/Dashboard/Tiles/Apps/AppTile.tsx
  src/modules/Docker/ContainerActionBar.tsx
  src/types/app.ts
Labels: ✨ Feature

#1244 💄 Improve sizing of app name
  src/components/Dashboard/Tiles/Apps/AppTile.tsx
Labels: 🐛 Bug

#1228 🥅 Add 404 error page
  public/locales/en/layout/errors/not-found.json
  src/images/undraw_page_not_found_re_e9o6.svg
  src/pages/404.tsx
  src/tools/server/translation-namespaces.ts
Labels: ✨ Feature

#1256 🐛 App Transparency not used by torrent tile table
  src/widgets/torrent/TorrentQueueItem.tsx
  src/widgets/torrent/TorrentTile.tsx
Labels: 🐛 Bug

#1236 ✨ Option to show time for a city
  package.json
  public/locales/en/modules/date.json
  src/components/Dashboard/Tiles/Widgets/WidgetsEditModal.tsx
  src/pages/_app.tsx
  src/server/api/root.ts
  src/server/api/routers/timezone.ts
  src/tools/language.ts
  src/widgets/date/DateTile.tsx
  src/widgets/widgets.ts
  yarn.lock
Labels: ✨ Feature

#1255 App tile flex fix
  public/locales/en/layout/modals/add-app.json
  src/components/Dashboard/Modals/EditAppModal/EditAppModal.tsx
  src/components/Dashboard/Modals/EditAppModal/Tabs/AppereanceTab/AppereanceTab.tsx
  src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
  src/components/Dashboard/Tiles/Apps/AppPing.tsx
  src/components/Dashboard/Tiles/Apps/AppTile.tsx
  src/modules/Docker/ContainerActionBar.tsx
  src/tools/config/getFrontendConfig.ts
  src/types/app.ts
Labels: 🐛 Bug

#1260 🐛 Issue with media request url
  src/server/api/routers/media-request.ts
Labels: 🐛 Bug

#1005 🐛 AdGuard Home time unit fix
  src/server/api/routers/dns-hole/router.ts
  src/tools/server/sdk/adGuard/adGuard.schema.ts
  src/tools/server/sdk/adGuard/adGuard.ts
  src/widgets/dnshole/DnsHoleSummary.tsx
Labels: 🐛 Bug

#1261 💄DNS Hole Stats Flex layout and text fitting
  public/locales/en/modules/dns-hole-summary.json
  src/pages/_app.tsx
  src/server/api/root.ts
  src/server/api/routers/dns-hole/router.ts
  src/tools/client/math.ts
  src/widgets/dnshole/DnsHoleSummary.tsx
Labels: ✨ Feature

#962 Notebook-widget
  package.json
  public/locales/en/modules/notebook.json
  src/components/Dashboard/Tiles/GenericTileMenu.tsx
  src/components/Dashboard/Tiles/Widgets/WidgetsEditModal.tsx
  src/server/api/root.ts
  src/server/api/routers/notebook.ts
  src/tools/server/translation-namespaces.ts
  src/widgets/index.ts
  src/widgets/notebook/NotebookEditor.tsx
  src/widgets/notebook/NotebookWidgetTile.tsx
  src/widgets/widgets.ts
  yarn.lock
Labels: ✨ Feature, 🛠️ WIP, 🎴 Widget

#1264 Fix issues with URL being too long when pinging many apps
  src/components/Dashboard/Tiles/Apps/AppPing.tsx
  src/server/api/routers/app.ts
  src/utils/api.ts
Labels: ✨ Feature, 🏛️ Architecture

#1269 🐛 Fix animation overflow
  src/components/Dashboard/Tiles/Apps/AppTile.tsx
Labels: 🐛 Bug

#1226 🥅 Add 500 catching page
  src/images/undraw_bug_fixing_oc-7-a.svg
  src/pages/_error.tsx
Labels: ✨ Feature, 🏛️ Architecture

#1295 ♻️ Onboarding page
  .env.example
  .gitignore
  package.json
  public/imgs/app-icons/truenas.svg
  public/imgs/app-icons/unraid-alt.svg
  src/components/Onboarding/common-wrapper.tsx
  src/components/Onboarding/onboarding-steps.tsx
  src/components/Onboarding/step-create-account.tsx
  src/components/Onboarding/step-docker-import.tsx
  src/components/Onboarding/step-documentation.tsx
  src/components/Onboarding/step-onboarding-finished.tsx
  src/components/Onboarding/step-update-path-mappings.tsx
  src/pages/onboard.tsx
  yarn.lock
Labels: 📄 Docs, ✨ Feature
