Repository ajnart/homarr, pull requests merged in 2023-09, with the labels that each got.

#1265 ✨Auth Page Dark/Light mode toggle button
  src/components/ThemeSchemeToggle/ThemeSchemeToggle.tsx
  src/pages/auth/invite/[inviteId].tsx
  src/pages/auth/login.tsx
  src/pages/onboard.tsx
Labels: ✨ Feature

#1333 Fix enable/disable edit mode
  src/components/Dashboard/Modals/AboutModal/AboutModal.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/SettingsMenu.tsx
  src/components/layout/header/SettingsMenu/EditModeToggle.tsx
  src/hooks/useEditModeInformation.ts
  src/modules/Docker/ContainerActionBar.tsx
  src/pages/_app.tsx
  src/pages/api/configs/[slug].ts
  src/pages/api/configs/tryPassword.tsx
  src/server/api/routers/config.ts
  src/server/api/routers/notebook.ts
Labels: 🐛 Bug, 🚨 Security Risk

#1276 ✨ Readd possibility to add containers as apps to boards
  public/locales/en/tools/docker.json
  src/components/Dashboard/Modals/SelectElement/Components/Overview/AvailableElementsOverview.tsx
  src/components/Manage/Tools/Docker/ContainerActionBar.tsx
  src/components/Manage/Tools/Docker/ContainerState.tsx
  src/components/Manage/Tools/Docker/ContainerTable.tsx
  src/components/Manage/Tools/Docker/docker-select-board.modal.tsx
  src/components/layout/Templates/BoardLayout.tsx
  src/modals.ts
  src/modules/Docker/DockerModule.tsx
  src/pages/manage/tools/docker.tsx
  src/server/api/routers/board.ts
  src/server/api/routers/config.ts
  src/tools/shared/app.ts
Labels: ✨ Feature

#1386 🩺 Added healthcheck to image and ARG for port
  Dockerfile
Labels: ✨ Feature

#1397 💄 Change modal for torrent widget
  src/widgets/torrent/TorrentQueueItem.tsx
Labels: ✨ Feature

#1384 ✨ Hide DNS-Hole control buttons option
  public/locales/en/modules/dns-hole-controls.json
  src/widgets/dnshole/DnsHoleControls.tsx
Labels: ✨ Feature

#1408 Add autofocus for searchbar
  prisma/schema.prisma
  public/locales/en/user/preferences.json
  src/components/User/Preferences/SearchEngineSelector.tsx
  src/components/layout/Templates/BoardLayout.tsx
  src/components/layout/Templates/MainLayout.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/Search.tsx
  src/pages/user/preferences.tsx
  src/server/api/routers/user.ts
  src/server/auth.ts
  src/validations/user.ts
Labels: 🐛 Bug, ✨ Feature

#1392 Feature/add allow anonymous switch
  package.json
  public/locales/en/settings/customization/access.json
  public/locales/en/settings/customization/general.json
  src/components/Board/Customize/Access/AccessCustomization.tsx
  src/components/Board/Customize/Appearance/AppearanceCustomization.tsx
  src/components/Board/Customize/form.ts
  src/pages/board/[slug].tsx
  src/pages/board/[slug]/customize.tsx
  src/pages/board/index.tsx
  src/server/api/routers/config.ts
  src/tools/config/getConfig.ts
  src/tools/config/getFallbackConfig.ts
  src/types/settings.ts
  src/validations/boards.ts
  tests/pages/board/[slug].spec.ts
  vitest.config.ts
  yarn.lock
Labels: ✨ Feature

#1416 Feat/add login redirection
  .github/workflows/docker_dev.yml
  package.json
  public/locales/en/authentication/login.json
  src/pages/auth/login.tsx
  src/pages/board/[slug].tsx
  src/pages/manage/boards/index.tsx
  src/pages/manage/users/create.tsx
  src/tools/server/loginBuilder.ts
  tests/pages/auth/login.spec.ts
  tests/pages/board/[slug].spec.ts
  vitest.config.ts
  yarn.lock
Labels: ✨ Feature

#1439 🐛 Remove DISABLE_EDIT_MODE and replace with admin-procedure
  src/server/api/routers/config.ts
  src/server/api/routers/notebook.ts
Labels: 🐛 Bug
