Repository ajnart/homarr, pull requests merged in 2024-01, with the labels that each got.

#1796 Fixes documentation link URL after creating user
  data/default.json
  src/components/Onboarding/database-not-writeable.tsx
  src/components/Onboarding/step-onboarding-finished.tsx
Labels: 🐛 Bug

#1794 Add availability information about media requests
  public/locales/en/modules/media-requests-list.json
  src/server/api/routers/media-request.ts
  src/widgets/media-requests/MediaRequestListTile.tsx
  src/widgets/media-requests/media-request-types.tsx
Labels: ✨ Feature

#1799 feature: trigger automations
  public/locales/en/modules/smart-home/entity-state.json
  public/locales/en/modules/smart-home/trigger-automation.json
  src/server/api/routers/smart-home/entity-state.ts
  src/tools/server/sdk/homeassistant/HomeAssistant.ts
  src/tools/server/translation-namespaces.ts
  src/widgets/index.ts
  src/widgets/smart-home/entity-state/entity-state.widget.tsx
  src/widgets/smart-home/trigger-automation/trigger-automation.widget.tsx
Labels: ✨ Feature, 🎴 Widget

#1798 feature: #1765 reduce transferred torrent data
  src/server/api/routers/download.ts
  src/types/api/downloads/queue/NormalizedDownloadQueueResponse.ts
  src/widgets/torrent/TorrentQueueItem.tsx
  src/widgets/torrent/TorrentTile.tsx
Labels: ⚡Performance

#1806 fix: database is not initialized inside the docker container
  Dockerfile
Labels: 🐛 Bug

#1810 feature: rss improvements
  public/locales/en/modules/rss.json
  src/server/api/routers/rss.ts
  src/widgets/rss/RssWidgetTile.tsx
Labels: 🐛 Bug

#1800 feature: board operations
  public/locales/en/manage/boards.json
  src/components/Dashboard/Modals/RenameBoard/RenameBoardModal.tsx
  src/modals.ts
  src/pages/manage/boards/index.tsx
  src/server/api/routers/board.ts
  src/server/api/routers/config.ts
  src/validations/boards.ts
Labels: ✨ Feature

#1818 feature: add trpc openapi
  package.json
  public/locales/en/layout/manage.json
  src/components/Manage/User/Edit/ManageUserRoles.tsx
  src/components/layout/Templates/ManageLayout.tsx
  src/pages/api/[...trpc].ts
  src/pages/api/openapi.json.ts
  src/pages/manage/tools/swagger.tsx
  src/pages/manage/users/[userId]/edit.tsx
  src/server/api/routers/app.ts
  src/server/api/routers/board.ts
  src/server/api/routers/config.ts
  src/server/api/routers/icon.ts
  src/server/api/routers/invite/invite-router.ts
  src/server/api/routers/user.ts
  src/server/api/trpc.ts
  src/server/openai.ts
  src/styles/global.scss
  yarn.lock
Labels: 📄 Docs, ✨ Feature
