Repository ajnart/homarr, pull requests merged in 2024-02, with the labels that each got.

#1868 fix: #1859 dayjs locale translation
  src/pages/_app.tsx
  src/tools/language.ts
Labels: ✨ Feature

#1807 Indexer manager
  public/locales/en/modules/indexer-manager.json
  src/components/Dashboard/Modals/EditAppModal/Tabs/IntegrationTab/Components/InputElements/IntegrationSelector.tsx
  src/server/api/root.ts
  src/server/api/routers/indexer-manager.ts
  src/tools/server/translation-namespaces.ts
  src/types/app.ts
  src/widgets/index.ts
  src/widgets/indexer-manager/IndexerManagerTile.tsx
Labels: 🎴 Widget

#1913 feat: add environment variable to overwrite oidc scopes
  src/env.js
  src/utils/auth/oidc.ts
Labels: 🐛 Bug

#1911 Fix redirect OIDC
  src/pages/api/auth/[...nextauth].ts
  src/pages/auth/login.tsx
  src/server/auth.ts
  src/utils/auth/index.ts
  src/utils/auth/oidc-redirect.spec.ts
  src/utils/auth/oidc.ts
Labels: 🐛 Bug
