Repository ajnart/homarr, pull requests merged in 2024-04, with the labels that each got.

#1996 :bug: Added playsInline to VideoBackground
  src/components/layout/Templates/BoardLayout.tsx
Labels: 🐛 Bug

#2017 feat: add romanian language support
  src/tools/language.ts
Labels: ✨ Feature

#1882 :sparkles: Add Tdarr integration and widget
  public/locales/en/modules/media-transcoding.json
  src/components/Board/Customize/Appearance/AppearanceCustomization.tsx
  src/components/Dashboard/Modals/EditAppModal/Tabs/IntegrationTab/Components/InputElements/IntegrationSelector.tsx
  src/components/Dashboard/Tiles/Widgets/WidgetsEditModal.tsx
  src/components/Dashboard/Tiles/Widgets/WidgetsMenu.tsx
  src/server/api/root.ts
  src/server/api/routers/tdarr.ts
  src/tools/server/translation-namespaces.ts
  src/types/api/tdarr.ts
  src/types/app.ts
  src/widgets/index.ts
  src/widgets/media-transcoding/HealthCheckStatus.tsx
  src/widgets/media-transcoding/MediaTranscodingTile.tsx
  src/widgets/media-transcoding/QueuePanel.tsx
  src/widgets/media-transcoding/StatisticsPanel.tsx
  src/widgets/media-transcoding/WorkersPanel.tsx
  src/widgets/widgets.ts
Labels: 🎴 Widget
