Repository ajnart/homarr, pull requests merged in 2024-03, with the labels that each got.

#1948 feat: add ldap search scope
  src/env.js
  src/utils/auth/ldap.ts
Labels: 🐛 Bug, ✨ Feature

#1953 fix: death links in readme
  README.md
Labels: 📄 Docs

#1951 ⚡️ Improve TorrentTile rendering performance
  src/widgets/torrent/TorrentTile.tsx
Labels: ✨ Feature, ⚡Performance

#1955 Fix death app links
  src/components/layout/Templates/BoardLayout.tsx
  src/components/layout/Templates/ManageLayout.tsx
Labels: 📄 Docs
